name: "Test Action"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # test action works running from the graph
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: is_organization_member_positive
        with:
          organization: kata-containers
          username: fidencio
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log Result
        run: |
          result=${{steps.is_organization_member_positive.outputs.result}}
          echo "$result"
      - uses: actions/checkout@v2
      - uses: ./
        id: is_organization_negative
        with:
          organization: openshift
          username: fidencio
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log Result
        run: |
          result=${{steps.is_organization_negative.outputs.result}}
          echo "$result"
